wtmm_daemon: PORT=8080 cargo run --quiet --bin wtmm_daemon
wtmm_courier: POSTMARK_API_TOKEN=POSTMARK_API_TEST cargo run  --quiet --bin wtmm_courier
wtmm_reporter: cargo run --quiet --bin wtmm_reporter 
