version: 2.1
parameters:
  should_provision:
    description: "Should the ansible provision playbook run?"
    type: boolean
    default: false
jobs:
  build:
    docker:
      - image: eanyanwu/wtmm:latest
        auth:
          username: eanyanwu
          password: $DOCKER_ACCESS_TOKEN
    resource_class: small 
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-cargo-deps-{{ checksum "wtmm/Cargo.lock" }}
      - run: make build
      - save_cache:
          paths:
            - wtmm/target
          key: v2-cargo-deps-{{ checksum "wtmm/Cargo.lock" }}
      - run: make test
      - store_artifacts:
          path: /tmp/workspace
          destination: artifact
  deploy:
    docker:
      - image: eanyanwu/wtmm:latest
        auth:
          username: eanyanwu
          password: $DOCKER_ACCESS_TOKEN
    resource_class: medium 
    steps:
      - checkout
      - add_ssh_keys
      - restore_cache:
          keys:
            - v3-cargo-release-{{ checksum "wtmm/Cargo.lock" }}
      - run: make build-release
      - save_cache:
          paths:
            - wtmm/release
          key: v3-cargo-release-{{ checksum "wtmm/Cargo.lock" }}
      - run: cd wtmm/release/release && cp wtmm_reporter wtmm_daemon wtmm_courier ../../../ansible/roles/deploy/files/bin
      - run: 'if [ "$CIRCLE_BRANCH" == "main" ]; then make ansible-deploy-prod; else make ansible-deploy; fi'
  provision:
    docker:
      - image: eanyanwu/wtmm:latest
        auth:
          username: eanyanwu
          password: $DOCKER_ACCESS_TOKEN
    resource_class: small
    steps:
      - checkout
      - add_ssh_keys
      - run: make ansible-provision

workflows:
  on-branch-push:
    jobs:
      - build
      - deploy:
          requires:
            - build
  on-provision:
    when: << pipeline.parameters.should_provision >>
    jobs:
      - provision