- name: add user public key
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ public_key }}"
- name: sshd configuration
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    # - regexp: "^#?PermitRootLogin"
    #   line: "PermitRootLogin no"
    - regexp: "^^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
- name: restart sshd
  systemd:
    state: restarted
    daemon_reload: yes
    name: sshd