- name: ensure application folder exists 
  ansible.builtin.file:
    path: "{{ application_folder }}"
    state: directory
    mode: 0755
- name: Ensure user lingering enabled
  command:
    cmd: "loginctl enable-linger {{ ansible_user }}"
    creates: ~/user-lingering
- name: copy binaries
  ansible.builtin.copy:
    src: bin/
    dest: "{{ application_folder }}"
    mode: 0755
- name: copy service files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0664
  with_items:
    - dest: "~/.config/systemd/user/{{ application_name }}_server.service"
      src: wtmm_server.service
    - dest: "~/.config/systemd/user/{{ application_name }}.target"
      src: wtmm.target
    - dest: "~/.config/systemd/user/{{ application_name }}_backup.timer"
      src: sqlite_backup.timer
    - dest: "~/.config/systemd/user/{{ application_name }}_backup.service"
      src: sqlite_backup.service
- name: start binary 
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ application_name }}.target"
    enabled: yes
    state: restarted
    scope: user
