---
- name: Deploy
  hosts: all
  remote_user: deploy-user

  vars:
    env: "dev"
    env_api_token_map:
      dev: "{{ lookup('env', 'POSTMARK_API_TOKEN_DEV') }}" 
      prod: "{{ lookup('env', 'POSTMARK_API_TOKEN') }}"
    env_application_name_map:
      dev: dev_wtmm
      prod: wtmm
    env_wtmm_server_port_map:
      dev: 5001
      prod: 5000 
    env_email_domain_map:
      dev: "dev.whotookmy.money"
      prod: "whotookmy.money"
    env_wtmm_mac_key_map:
      dev: RpWmx32XfrKLlHMzdiDVnSSIjZX6gzQw3YKY9Tf+Nts=
      prod: "{{ lookup('env', 'WTMM_MAC_KEY') }}"

    postmark_api_token: "{{ env_api_token_map[env] }}"
    application_name: "{{ env_application_name_map[env] }}"
    application_folder: ".{{ application_name }}"
    wtmm_server_port: "{{ env_wtmm_server_port_map[env] }}"
    email_domain: "{{ env_email_domain_map[env] }}"
    wtmm_mac_key: "{{ env_wtmm_mac_key_map[env] }}"
    aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    aws_default_region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"

  roles:
    - deploy
